//
//  Supermarket.swift
//  comittea
//
//  Created by Atyanta Awesa Pambharu on 27/06/22.
//

import Foundation

struct Supermarket: Storiable {
    let story = Story("Supermarket", "Monthly groceries shopping time!",  "Story_Logo_Supermarket",  "Story_Background_Supermarket", [
        Chapter("Monthly Groceries", "Chapter_Monthly", "Find The Banana",
        [
            CompyConversationMessage("What day is it today?"),
            UserConversationMessage("It's Sunday"),
            CompyConversationMessage("First Sunday in the month! You know what do you have to do, right?"),
            UserConversationMessage("Oh you're right. Monthly groceries shopping."),
            CompyConversationMessage("Have you made a list of what you should buy?"),
            UserConversationMessage("Not yet ☹️"),
            CompyConversationMessage("Don't worry! You have me. I will help you to make a list"),
            MultiSelectMessage(
                "Which one do you think it's better?",
                [
                    "Sugar",
                    "Cooking oil",
                    "Lipstick",
                    "Cereals",
                    "Milk",
                    "Jewelry",
                    "Egg",
                    "Banana",
                    "Flowers",
                    "Nugget",
                    "Instant noodle",
                    "Mirror",
                    "Meat",
                    "Fish",
                    "Powerbank",
                ],
                [
                    "Sugar",
                    "Cooking oil",
                    "Cereals",
                    "Milk",
                    "Egg",
                    "Banana",
                    "Nugget",
                    "Instant noodle",
                    "Meat",
                    "Fish",
                ],
                CompyTrueMessage("Wow, that's correct! You already know which things that you should buy when you do monthly groceries shopping. You know what, you have done one activity of computational thinking, abstraction. You focus on the idea and information, ignoring irrelevant details. You didn't pick unnecessary things that you shouldn't buy in monthly groceries shopping."),
                CompyFalseMessage("Hmm it seems you pick the wrong one. Try to focus on the idea and information. Things you should buy in monthly groceries shopping. Do you think it's necessary to buy Flowers, Powerbank, Mirror, Lipstick, Jewelry when you do monthly groceries shopping? I don't think so. We don't always restock those things every month, right? But, that's okay! Now you know that you should ignoring irrelevant details and try to focus on the key information."), false),
                CompyConversationMessage("You have made the list! It's pretty easy, isn't it?"),
                UserConversationMessage("Yes. It helps me to didn't buy unnecessary things too."),
                CompyConversationMessage("Yep. You should focus on the specific things and ignoring irrelevant details."),
                UserConversationMessage("You are right. Sometimes when I got too broad information, it's pretty hard to narrowing the thing."),
                CompyConversationMessage("Of course~ Focus is the key."),
                CompyConversationMessage("We are going to supermarket today, right?"),
                UserConversationMessage("Right. Let's go!"),
                CompyConversationMessage("Wait. You sure you didn't forget something?"),
                UserConversationMessage("I don't think so"),
                CompyConversationMessage("You didn't bring anything?"),
                UserConversationMessage("What should I bring? I can just bring myself and my phone and all done."),
                CompyConversationMessage("How do you bring your groceries later?"),
                UserConversationMessage("Can't I just bring them with my hands?"),
                CompyConversationMessage("Really? You sure you can handle it?"),
                SingleChoiceMessage(
                    "Which one do you think it's better?",
                    ["Bring the shopping bag", "Bring the shopping bag", "Just bring the groceries with bare hands",],
                    "Bring the shopping bag",
                    CompyTrueMessage("That's right! You didn't want your hands bothered with many things, do you? We just have two hands, how we can handle ten items in our hands. We can solve the problem by bring the shopping bag. With the shopping bag, we can just put all of the items together and easily packed. Unconsciously, you have solved the problem with decomposition, it's when you breaking down a complex problem into smaller part to carry it."),
                    CompyFalseMessage("Are you sure you can bring the ten items just with your bare hands? Imagine you bring the egg, apple, milk, cereals with only one hand. It seems troublesome. You can put the groceries items in the shopping bag and it's simply packed, problem solved. Your hands won't be bothered with many things."),
                    false
                ),
                CompyConversationMessage("That's good! Now don't forget to bring your shopping bag."),
                UserConversationMessage("Ay-ay, Captain! Thank you for helping me."),
                CompyConversationMessage("Anytime, %@! You also did a great job too~"),
                CompyConversationMessage("Now, we have done two activities with different concept of computational thinking."),
                CompyConversationMessage("Can you differentiate it?"),
                SingleChoiceMessage(
                    "When you want to solve the problem, you must focus on key information. That is the concept of?",
                    ["Decomposition", "Abstraction"],
                    "Abstraction",
                    CompyTrueMessage("Good job! You can differentiate between abstraction and decomposition. Abstraction is when we should focus on information and ignoring irrelevant details, while decomposition is we can breaking down the problem into smaller, manageable parts. I'm really proud of you. Keep it up! 🤩"),
                    CompyFalseMessage("The correct answer is abstraction. Abstraction is when we should focus on information and ignoring irrelevant details, while decomposition is we can breaking down the problem into smaller, manageable parts. It's okay, now try to plant that concept so you can go further!"),
                    false
                ),
                UserConversationMessage("Thank you so much, Compy. Now I know the differences between abstraction and decomposition."),
                CompyConversationMessage("Don't mention it. Okay now bring your shopping bag and let's go to the supermarket!"),
                UserConversationMessage("Already! Eh, should I only bring one shopping bag?"),
                CompyConversationMessage("Yes. I think one large-sized shopping bag could handle ten items that you want to buy."),
                UserConversationMessage("But, there's a problem"),
                CompyConversationMessage("What is the problem?"),
                UserConversationMessage("Meat and fish are smelly. I don't want the other stuffs mixed with their smells."),
                CompyConversationMessage("Hmmm.. You're right"),
                UserConversationMessage("What should I do then?"),
                SingleChoiceMessage(
                        "What will you do to solve that problem?",
                        ["Bring seperate shopping bag special for meat and fish", "Just bring one shopping bag, I can carry the meat and fish with my bare hands.", "I didn't need shopping bag. I can use the trolley and move my things one by one to my car so it's seperated already."],
                        "Bring seperate shopping bag special for meat and fish",
                        CompyTrueMessage("Couldn't agree more! We should bring seperate shopping bag special only for meat and fish. With that, we can prevent the smells from spreading. You just breaked down the complex problem into manageable parts. Do you remember what computational thinking's concept it is? Yep, that's decomposition~"),
                        CompyFalseMessage("I don't think so. Isn't your choice will make more problem? It will be troublesome for you. Remember, we are here to solve the problem with the most simple way. Bring the seperate shopping bag special for meat and fish is the most effective way. You can still simply handled it with that."),
                        false),
                    CompyConversationMessage("You are really great, %@. "),
                    UserConversationMessage("I can't do that without your help, Compy."),
                    CompyConversationMessage("No, it's not because of me. It's because of you. You are the one who solved the problem."),
                    UserConversationMessage("So we can go to supermarket now?"),
                    CompyConversationMessage("Sure. But, before we go to the supermarket, can we review it one more time?"),
                    UserConversationMessage("No worries. Bring me more question, please."),
                    SingleChoiceMessage(
                        "When you want to cook fried noodle, your mind will be automatically know that you should prepare ingredients to make it. There will be instant noodle, egg, cooking oil, and nugget. That's why you go to supermarket to buy those things. This is one example of the concept of?",
                        ["Decomposition", "Abstraction"],
                        "Decomposition",
                        CompyTrueMessage("Congratulations! You passed this chapter smoothly. You are right, that is the concept of decomposition. It can be seen from the way you breaked down the things that will be ingredients to cook fried noodle."),
                        CompyFalseMessage("That's the concept of decomposition, %@. Remember, Abstraction is when we should focus on information and ignoring irrelevant details. While decomposition is we can breaking down the problem into smaller manageable parts."), false),
        ]),
        Chapter("Find The Banana", "Chapter_Banana", "Pay Lane", [
            NarrationMessage("You go to supermarket with your car. Now, you are already here, at the supermarket. Let's park your car and get ready to enter the supermarket."),
            CompyConversationMessage("Let's park your car!"),
            UserConversationMessage("Working on it!"),
            CompyConversationMessage(" Hey. %@. Everytime you park your car, you've never been in trouble for illegal parking, have you?"),
            UserConversationMessage("Of course. I am an obedient citizen."),
            CompyConversationMessage("Good, good! That means you can always find the parking area."),
            UserConversationMessage("I am. I'm always neat in parking my car."),
            CompyConversationMessage("How can you always find the parking area even though that was your first time visit the place?"),
            UserConversationMessage("Oh, you are right. Do we call it intuition?"),
            CompyConversationMessage("No. That's not intuition."),
            UserConversationMessage("So, what is it then?"),
            SingleChoiceMessage(
                "How do you think people can find the parking area even though it was first time they visit the place?",
                ["They are using intuition", "People see the pattern, when there's a bunch of cars with engine off lined up in specific area, that's definitely the parking area.", "They just park it anywhere in available space without thinking anything more."],
                "People see the pattern, when there's a bunch of cars with engine off lined up in specific area, that's definitely the parking area.",
                CompyTrueMessage("You're correct! Subconsciously, we can tell if it's a parking lot or not by looking around whether there's car parked there or not. How can we know the car is parked? Just look at the pattern, when there's a bunch of cars with engine off lined up in specific area, that's definitely the parking area. It's called pattern recognition. We can recognize something just by looking at the pattern"),
                CompyFalseMessage("Your answer is not correct. We park our car in parking area. How can we know that's a parking area? Because we see the pattern. Pattern that there's a bunch of cars with engine off lined up in specific area. When we recognised the pattern, we know that is a parking area. It's called pattern recognition."),
                false),
            CompyConversationMessage("The supermarket is super huge"),
            UserConversationMessage("Yeah we can find everything here. That's why it's called SUPERmarket"),
            CompyConversationMessage("Do you have enough time to search all of the stuffs that you want to buy?"),
            UserConversationMessage("I have problem with that. I need save time because in an hour, I have an online meeting."),
            CompyConversationMessage("That's very tight."),
            UserConversationMessage("Can you help me, Compy?"),
            CompyConversationMessage("Let's take a look around to save the time so we can get the stuffs quickly."),
            UserConversationMessage("Can we just ask the employee where's the stuff that we need?"),
            CompyConversationMessage("They just tell us the direction, without we even know which rack"),
            UserConversationMessage("So what should I do?"),
            CompyConversationMessage("Did you notice something the sign in the top of the rack?"),
            UserConversationMessage("I see it!"),
            SingleChoiceMessage(
                "When we notice that there's sign in the top of the rack, what concept of this?",
                ["Abstraction", "Decomposition", "Pattern recognition"],
                "Pattern recognition",
                CompyTrueMessage("Goood job~ Yes, that's called pattern recognition. The sign help us to find the stuff that we need from its category by the section. We can find the similarities and repition on that."),
                CompyFalseMessage("Tet-net! The correct answer is pattern recognition.  The sign help us to find the stuff that we need from its category by the section. We can find the similarities and repition on that."),
                false),
            CompyConversationMessage("Let's see what should we buy from the list that we have made before."),
            UserConversationMessage("Sugar, Cooking oil, Cereals, Milk, Egg, Banana, Nugget, Instant noodle, Meat, Fish"),
            CompyConversationMessage("Fruit in section A, breakfast needs in section B, frozen food in section C, meat and fish in section D, groceries in section E"),
            CompyConversationMessage("Section A is the nearest to our start point, while section E is the further."),
            UserConversationMessage("But, I need to put fresh stuffs that out from refrigerator as the last item that we took"),
            UserConversationMessage("So at least they don't stay out of the fridge for too long"),
            CompyConversationMessage("Let's arrange where section that we should go first"),
            ReorderMessage(
                "Let's arrange the item! Don't forget to pay attention to the order of sections", [
                    "Sugar, cooking oil, instant noodle, egg",
                    "Banana",
                    "Meat and fish",
                    "Nugget",
                    "Cereals, milk"
                ],
                [
                    "Banana",
                    "Cereals, milk",
                    "Sugar, cooking oil, instant noodle, egg",
                    "Nugget",
                    "Meat and fish"
                ],
                CompyTrueMessage("Great job! This question is layered question. If you pay attention. Compy explained that the sections are sequential start from section A until section E. But, you must put fresh stuffs that out from refrigerator as the last item that we took. Nugget, meat and fish is the frozen item, right? So, why nugget first? Because nugget in section C, while meat and fish in section D. "),
                CompyFalseMessage("""
                That's not quite right but that is okay! This question is layered question. If you pay attention. Compy explained that the sections are sequential start from section A until section E. But, you must put fresh stuffs that out from refrigerator as the last item that we took. Nugget, meat and fish is the frozen item, right? So, why nugget first? Because nugget in section C, while meat and fish in section D. So the correct order is
                - Banana
                - Cereals, milk
                - Sugar, cooking oil, instant noodle, egg
                - Nugget
                - Meat and fish"
                """),
                false
            ),
            UserConversationMessage("Let's take a look to the list"),
            CompyConversationMessage("Didn't we already arrange it?"),
            UserConversationMessage("Oh, you are right. Okay let's find the banana"),
            SingleChoiceMessage(
                "I should go to fruit section to find the banana",
                ["True", "False"],
                "True",
                CompyTrueMessage("Of course~ We know the pattern that section is divided by its category. So we should go to fruit section to find the banana."),
                CompyFalseMessage("Hmm I don't think so. We should go to fruit section to find the banana, do we?"),
                false),
            CompyConversationMessage("Here we are in fruit section. Let's find the banana"),
            UserConversationMessage("Compy, isn't bananas spoil easily because we can't store them in the refrigerator?"),
            CompyConversationMessage("Yep. So we must find the fit banana"),
            UserConversationMessage("But, I want to save time and energy because the meeting will be start in minutes."),
            SingleChoiceMessage(
                "What the most effective what that should I do to save time and energy but still get banana with good condition?",
                ["I should choose from the bottom of the rack", "I can choose banana that placed in the top. I can only use my eyes to skimming which banana that in good condition"],
                "I can choose banana that placed in the top. I can only use my eyes to skimming which banana that in good condition",
                CompyTrueMessage("Great! When choosing banana, we will choose that placed in the top. It will be wasting time a lot if we must pick the banana from the bottom of the rack. The top banana is the last banana to be placed. So, the top banana is the most fresh one, right? That's the concept of Stack, Last in First Out. The last banana that be placed, is the first Banana that we will take."),
                CompyFalseMessage("Are you sure you will choose them from the bottom of the rack? Isn't it will be wasting time? When choosing banana, we will choose that placed in the top. It will be wasting time a lot if we must pick the banana from the bottom of the rack. The top banana is the last banana to be placed. So, the top banana is the most fresh one, right? That's the concept of Stack, Last in First Out. The last banana that be placed, is the first Banana that we will take."),
                false),
        ]),
        Chapter("Pay Lane", "Chapter_PayLine", "", [
            NarrationMessage("Congratulations! You have done took the stuffs that you need to buy. Now, let's pay it in the cashier"),
            CompyConversationMessage("Wow, that's a lot of cashier here"),
            CompyConversationMessage("The cashier also divided by the category of payment method"),
            UserConversationMessage("Really? So we couldn't do the any cashier that we want?"),
            CompyConversationMessage("Yep. Cashier 1-3 for cash payment. Cashier 4-15 for cashless payment"),
            CompyConversationMessage("We should decide what payment method that we want to use"),
            CompyConversationMessage("What method do you want to use for paying?"),
            UserConversationMessage("Credit card"),
            SingleChoiceMessage(
                "You want to pay with credit card, where is the cashier that you should ignore?",
                ["Cashier 1-3", "Cashier 4-15"],
                "Cashier 1-3",
                CompyTrueMessage("You are absolutely correct. You want to pay it with credit card, that means cashless payment method. You should focus on that information and go to cashier 4-15. While cashier 1-3 is for cash method. That means, you should ignore cashier 1-3 because that is irrelevant details. This is concept for Abstraction."),
                CompyFalseMessage("That's not right answer. Don't forget to read the details in the question and conversations. You want to pay it with credit card, that means cashless payment method. You should focus on that information and go to cashier 4-15. While cashier 1-3 is for cash method. That means, you should ignore cashier 1-3 because that is irrelevant details. This is concept for Abstraction."),
                false
            ),
            CompyConversationMessage("Great. Now that's a lot of queue and looks so crowded"),
            UserConversationMessage("Huhu, my meeting will start in 15 minutes"),
            UserConversationMessage(" I want to pay it as soon as possible"),
            UserConversationMessage("Can you help me, Compy?"),
            CompyConversationMessage("With my pleasure. Now let's breaking it down first"),
            CompyConversationMessage("Lane 5, 7, 15 has only 2 people in the queue."),
            CompyConversationMessage("Lane 4, 13, 14 has 3 peoples."),
            CompyConversationMessage("Lane 8, 11, 12 has 4 peoples."),
            CompyConversationMessage("Lane 4, 6, 9, 10 has 5 peoples. "),
            UserConversationMessage("Why do we have to count the number of people in the lane?"),
            CompyConversationMessage("Because we have to queue"),
            CompyConversationMessage("The first people who get in the lane, will be the first people that out from the lane"),
            UserConversationMessage("I see. The fewer the better?"),
            UserConversationMessage("So we should pick between lane 5, 7, and 15."),
            CompyConversationMessage("Great. Now, let's focus on the queue."),
            SingleChoiceMessage(
                "Where cashier that you should to go to? The case is lane 5 has two people with 3 trolley. Lane 7 has two people with 1 trolley and 1 basket. Lane 15 has 2 trolley and 1 basket.",
                ["Lane 5", "Lane 7", "Lane 15"],
                "Lane 7",
                CompyTrueMessage("Excellent! We just breaked it down and see lane 7 is the shortest because only 2 people left with 1 trolley and 1 basket. As we know, when people have trolley, it has more items than people with the basket. So the lane with 1 trolley and 1 basket is probably has the less time to wait than other lane. When breaking it down to calculate which lane is short, you just doing decomposition activity in computational thinking."),
                CompyFalseMessage("The correct answer is Lane 7. We just breaked it down and see lane 7 is the shortest because only 2 people left with 1 trolley and 1 basket. As we know, when people have trolley, it has more items than people with the basket. So the lane with 1 trolley and 1 basket is probably has the less time to wait than other lane. When breaking it down to calculate which lane is short, you just doing decomposition activity in computational thinking."),
                false
            ),
            CompyConversationMessage("Finally we got the shortest lane!"),
            UserConversationMessage("Thank you, Compy, for helping me again."),
            CompyConversationMessage("I'm happy to help, %@."),
            UserConversationMessage("Compy, Why do we have to queue to pay it?"),
            CompyConversationMessage("They can't do the payment if there is more than one process done concurrently"),
            CompyConversationMessage("Because that's how the data works. We can only do it one by one sequentially."),
            CompyConversationMessage("In the programming, it's called Queue."),
            CompyConversationMessage("Queue have first in first out system"),
            CompyConversationMessage("Enqueue when adding data to the tail, dequeue when realising data from the head."),
            CompyConversationMessage("The first person entering the lane, will be the first out from the lane."),
            SingleChoiceMessage(
                "What Queue's operation concept that you use when you ENTERING the cashier lane?",
                ["Enqueue", "Dequeue"],
                "Enqueue",
                CompyTrueMessage("Yep that's right! Enqueue is entering the data. Dequeue is relased the data from the queue. When you entering the lane it means you are doing enqueue. While dequeue is when you are get out from the lane."),
                CompyFalseMessage("The correct answer is Enqueue. Enqueue is entering the data. Dequeue is relased the data from the queue. When you entering the lane it means you are doing enqueue. While dequeue is when you are get out from the lane."),
                false
            ),
            CompyConversationMessage("Now you have learned about queue and stack"),
            CompyConversationMessage("Queue is when you are in queue lane, first who got in the lane will be the first that will be out from the lane"),
            UserConversationMessage("How about another example about Stack?"),
            CompyConversationMessage("Stack is when you are doing dishes. When  you pile up the dishes to wash, you will take the top plate first to wash it"),
            CompyConversationMessage("You won't take the bottom one first because it will be troublesome"),
            CompyConversationMessage("Basically Stack is about who got in first, will be the last out"),
            UserConversationMessage("So Queue is First In First Out, while Stack is Last In First Out?"),
            CompyConversationMessage("You got it right!"),
            SingleChoiceMessage(
                "When you put your stuffs to the cashier desk, you will pick the top item first from your trolley. What algorithm concept that we use here?",
                ["Stack", "Queue", "Sorting", "Searching"],
                "Stack",
                CompyTrueMessage("You are totally correct! If we take a look more, the concept is Last In First Out. The last item that we put in our trolley, will be the first item we take to the cashier desk. So concept that we use aboce is Stack."),
                CompyFalseMessage("That's not right. If we take a look more, the concept is Last In First Out. The last item that we put in our trolley, will be the first item we take to the cashier desk. So concept that we use aboce is Stack."),
                false
            ),
            CompyConversationMessage("Good job, %@! Now you know about Stack and Queue algorithm concept."),
            CompyConversationMessage("It's your turn now. Let's wait cashier to scan your stuffs"),
            CompyConversationMessage("We should move the stuff that have been scanned to your shopping bag"),
            UserConversationMessage("On it!"),
            CompyConversationMessage("Okay now for the last activity to remember and put a deeper foundation for you"),
            SingleChoiceMessage(
                "When you put your stuffs that have been scanned in cashier to your shopping bag, you will move the first item that already scanned first. What algorithm concept that we use here?",
                ["Stack", "Queue", "Sorting", "Searching"],
                "Queue",
                CompyTrueMessage("Extremely correct! I'm really proud of you. Yes, it's true. It's the opposite side of when we put the groceries earlier, which is a stack activity. Now when we put the stuffs in the shopping bag, the activity will turn into a Queue. The concept of First In First Out."),
                CompyFalseMessage("Extremely correct! I'm really proud of you. Yes, it's true. It's the opposite side of when we put the groceries earlier, which is a stack activity. Now when we put the stuffs in the shopping bag, the activity will turn into a Queue. The concept of First In First Out."),
                false
            ),
        ])
    ])
}
